name: Deploy Node Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t shahabali323/github-node-cicid .
      - name: Publish Image
        run: Docker push shahabali323/github-node-cicid:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from the docker hub
        run: docker pull shahabali323/github-node-cicid:latest
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' shahabali323/github-node-cicid:latest
